version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description:  greenweez raw data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: raw sportswear sales
        tests:
          - unique:
              column_name:  "(orders_id||'-'||products_id)"
        columns:
          - name:  date_date
            description: date of order
          - name: orders_id
            description: id of the order
        
      - name: product
        identifier: raw_gz_product
        description: lists of products
        columns:
          - name: products_id
            tests:
            - unique
            - not_null
      - name: ship
        identifier: raw_gz_ship
        description:  shipment table
        columns:
          - name: orders_id
            description: PK of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: fees to subtract for operational margin
          - name: logcost
            description: cost to substract for operational margin
